# Site settings
baseURL = "http://epic2018cs.pysplash.org/"
languageCode = "en-us"
title = "Interactivity in Computer Science: EPIC 2018 Workshop"
theme = "hugo-simpledoc-theme"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

# Top menu
[[menu.top]]
    name = "View Workshop Slides"
    weight = 10
    url = "https://speakerdeck.com/willingc/interactivity-in-computer-science"
[[menu.top]]
    name = "View and Download Workshop PDF"
    weight = 20
    url = "https://github.com/willingc/epic-interactive/blob/master/epic-workshop.pdf"
[[menu.top]]
    name = "Original WPThemeDoc by Rich Tabor"
    weight = 30
    url = "https://github.com/richtabor/WPThemeDoc"

# Site parameters
[params]

    # Meta
    description = "hugo-simpledoc-theme - clean and convenient documentation theme for Hugo website generator"
    author = "Pavel Kanyshev"
    keywords = "hugo, documentation, hugo theme, hugo simple documentation theme"
    
    # Header
    # If not set, site title and meta description will be shown.
    # You may use markdown here
    headerTitle = "Interactivity in Computer Science\n EPIC 2018 Workshop"
    headerDescription = "Helpful links for EPIC 2018 Workshop using **p5.js** and **Project Jupyter**"
    
    # Back-to-top button name
    bttButton = "Back to Top"